### ISSUE TITLE
Throw exception `RangeError (index): Invalid value: Not in inclusive range 0..9: -1`  when drag someone.

### ISSUE THREAD

**Issue by parcool** [isaacselement/flutter_sortable_wrap#1]
Here is my code:
```
import 'package:flutter/material.dart';
import 'package:flutter_sortable_wrap/flutter_sortable_wrap.dart';
import 'package:collection/collection.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});


  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: CustomScrollView(
        cacheExtent: 0,
        slivers: [
          SliverPersistentHeader(
            pinned: true,
            floating: true,
            delegate: MyDelegate(),
          ),
        ],
      ),
    );
  }
}

class MyDelegate extends SliverPersistentHeaderDelegate {

  MyDelegate();

  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) {

    return SortableWrap(
      onSorted: (int oldIndex, int newIndex) {},
      children: List.generate(10, (index) => Text("MyItem$index")).toList(),
    );
  }

  @override
  double get maxExtent {
    return 200;
  }

  @override
  double get minExtent {
    return 200;
  }

  @override
  bool shouldRebuild(covariant MyDelegate oldDelegate) {
    return false;
  }
}

```

throws:
```
Debug service listening on ws://127.0.0.1:64645/l0DQ00g9XPA=/ws
Syncing files to device macOS...
flutter: 2023-10-11 17:52:42.722529 [Wrap] Drag start index: 6
flutter: 2023-10-11 17:52:42.725051 [Wrap] Context's size: Size(800.0, 20.0)
flutter: 2023-10-11 17:52:42.725160 [Wrap] Element's size: Size(60.0, 20.0)
flutter: 2023-10-11 17:52:42.725427 [Wrap] [START] count on per row: 13, count on per column: 1
flutter: 2023-10-11 17:52:42.725496 [Wrap] [FINAL] count on per row: 13, count on per column: 1

======== Exception caught by gesture library =======================================================
The following RangeError was thrown while routing a pointer event:
RangeError (index): Invalid value: Not in inclusive range 0..9: -1

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      ListEx.swap (package:flutter_sortable_wrap/sortable_utils.dart:19:23)
#2      SortableWrapState.eventDoRollingInDragging (package:flutter_sortable_wrap/sortable_wrap.dart:262:25)
#3      SortableItemState.build._capacityHit.<anonymous closure> (package:flutter_sortable_wrap/sortable_item.dart:121:25)
#4      _DragTargetState.didEnter (package:flutter/src/widgets/drag_target.dart:687:60)
#5      _DragAvatar.updateDrag.<anonymous closure> (package:flutter/src/widgets/drag_target.dart:846:23)
#6      ListBase.firstWhere (dart:collection/list.dart:126:15)
#7      _DragAvatar.updateDrag (package:flutter/src/widgets/drag_target.dart:840:91)
#8      _DragAvatar.update (package:flutter/src/widgets/drag_target.dart:790:5)
#9      MultiDragPointerState._move (package:flutter/src/gestures/multidrag.dart:92:16)
#10     MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:254:13)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#23     _invoke1 (dart:ui/hooks.dart:186:13)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
====================================================================================================

======== Exception caught by gesture library =======================================================
The following assertion was thrown while routing a pointer event:
'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 701 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      _DragTargetState.didLeave (package:flutter/src/widgets/drag_target.dart:701:12)
#3      _DragAvatar._leaveAllEntered (package:flutter/src/widgets/drag_target.dart:877:26)
#4      _DragAvatar.updateDrag (package:flutter/src/widgets/drag_target.dart:837:5)
#5      _DragAvatar.update (package:flutter/src/widgets/drag_target.dart:790:5)
#6      MultiDragPointerState._move (package:flutter/src/gestures/multidrag.dart:92:16)
#7      MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:254:13)
#8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#11     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
#16     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#17     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#20     _invoke1 (dart:ui/hooks.dart:186:13)
#21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

```

**Comment by SnowGirls** [comment]
@parcool  Thanks pointing out this issue, because of the `didUpdateWidget` was called when drag start . I'll fix it soon .

**Comment by parcool** [comment]
I'm so glad to hear that.

**Comment by SnowGirls** [comment]
@parcool fixed.

**Comment by parcool** [comment]
peeeeeerfect!
